# Programming assignment 8
## Joey Guthrie, Version 1, CS150 Spring 2023

In [2]:
import numpy as np
import math

In [3]:
a=np.array([[10,20],
            [30,40]])
           
    
b=2
c=np.array([100,100])
d=5
print(a**b)
print(a+c)
print(a*d)
print(np.sqrt(a))

[[ 100  400]
 [ 900 1600]]
[[110 120]
 [130 140]]
[[ 50 100]
 [150 200]]
[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [18]:
triplearray=np.arange(3,28,3)
array1=triplearray.reshape(3,3)
tentotwentyarray=np.linspace(10,20,9)
array2=tentotwentyarray.reshape(3,3)

In [20]:
print(array1)
print(array2)
print(array1*array2)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]
[[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


In [24]:
x1=np.load('process1.npy')
x2=np.load('process2.npy')
x3=np.load('process3.npy')
x4=np.load('process4.npy')
x5=np.load('process5.npy')
mergePhaseOne=np.concatenate([x1,x2])
mergePhaseTwo=np.concatenate([mergePhaseOne,x3])
mergePhaseThree=np.concatenate([mergePhaseTwo,x4])
gestalt=np.concatenate([mergePhaseThree,x5])
gestalt

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [26]:
print(np.mean(gestalt[:,0]))
print(np.mean(gestalt[:,1]))
print(np.mean(gestalt[:,2]))
print(np.mean(gestalt[:,3]))
print(np.mean(gestalt[:,4]))

72.0
27.8
45.6
12.0
47.8
